brew "vim"
brew "neovim"

# Silver Searcher
brew "ag"

# Fuzzy Finder
brew "fzf"

# Shellcheck
brew "shellcheck"

# Golang LSP
brew "gopls"

# Lua LSP
brew "lua-language-server"

# Terraform LSP
brew "terraform-lsp"
