brew "vim"
brew "neovim"

# Silver Searcher
brew "ag"

# Fuzzy Finder
brew "fzf"

# Golang LSP
brew "gopls"

# Lua LSP
brew "lua-language-server"

# Terraform LSP
brew "terraform-lsp"

# Bash LSP
brew "bash-language-server"
brew "shellcheck"
brew "shfmt"
